apiVersion: v1
kind: Pod
metadata:
  name: test
  # labels:
  #   wyq: Unschedulable
spec:
  schedulerName: wyq
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80

