apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  schedulerName: wyq
  volumes:
  - hostPath:
      path: /var/run/docker.sock
    name: dockersock
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
      - mountPath: /var/run/docker.sock
        name: dockersock
      env:
      - name: PUBLICIMAGE
        value: registry.cnbita.com:5000/wuyiqiang/python3.9_cuda11.3_pytorch1.12_tensorrt8.0_deepspeed:v1

