apiVersion: v1
kind: ConfigMap
metadata:
  name: test-scheduling-config
  namespace: kube-system
data:
   config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: wyq
      resourceNamespace: kube-system
    profiles:
    - schedulerName: wyq
      plugins:
        preFilter:
          enabled:
          - name: defalut
          - name: filteringPod
        filter:
          enabled:
          - name: defalut
          - name: filteringNode
        postFilter:
          enabled:
          - name: defalut
        preScore:
          enabled:
          - name: defalut
        score:
          disabled:
          - name: TaintToleration
          enabled:
          - name: ImageLocality
            weight: 10
          - name: randScore
            weight: 100
        reserve:
          enabled:
          - name: defalut
        permit:
          enabled:
          - name: defalut
        preBind:
          enabled:
          - name: defalut
        bind:
          enabled:
          - name: defalut
        postBind:
          enabled:
          - name: defalut
        


          