apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-scheduling
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-scheduling
  template:
    metadata:
      labels:
        app: test-scheduling
    spec:
      nodeName: yigou-dev-102-45
      serviceAccount: test-scheduling-sa
      containers:
        - name: tests-cheduling
          image: registry.cnbita.com:5000/wuyiqiang/wyq-scheduler:v1
          imagePullPolicy: Always
          command: ["wyq-scheduler"]
          args:
            - --config=/etc/kubernetes/config.yaml
            - --v=5
          volumeMounts:
            - name: config
              mountPath: /etc/kubernetes
      volumes:
        - name: config
          configMap:
            name: test-scheduling-config
---
# --v=5 不同等级的v可以控制日志打印的等级，v5 可以打印调度器所有插件的日志信息。